import { Flame, Leaf, MapPin, Phone, Star, UtensilsCrossed } from 'lucide-react';
import { galleryItems } from '../data/gallery';
import { menuItems } from '../data/menu';
import { restaurant, imagePaths } from '../data/restaurant';
import { BRAND_NAME } from '../data/brand';
import { reviews } from '../data/reviews';
import { ButtonLink, ImageWithFallback, SectionHeading } from './ui';
import { useLanguage } from '../i18n';

const dishes = [
  ['chicken-tikka', imagePaths.tikka], ['butter-chicken', imagePaths.butterChicken], ['rogan-josh', imagePaths.roganJosh],
  ['house-biryani', imagePaths.biryani], ['tandoori-mixed-grill', imagePaths.mixedGrill], ['palak-paneer', imagePaths.palakPaneer],
];

export function SignatureDishes() { const { language } = useLanguage(); const copy = language === 'fr' ? ['Les incontournables', 'Les saveurs de la maison', 'Six spécialités généreuses pour découvrir notre cuisine indienne et pakistanaise.', 'Spécialité'] : ['Signature dishes', 'Flavours of the house', 'Six generous specialities introducing our Indian and Pakistani cuisine.', 'Speciality']; return <section className="section home-dishes"><div className="container"><SectionHeading eyebrow={copy[0]} title={copy[1]} intro={copy[2]} /><div className="dish-grid">{dishes.map(([id, image]) => { const item = menuItems.find(entry => entry.id === id)!; const name = language === 'fr' ? item.name : item.englishName; return <article className="dish-card" key={id}><ImageWithFallback src={image} alt={name} loading="lazy" /><div><span className="badge">{copy[3]}</span><h3 className="notranslate" translate="no">{name}</h3><p>{language === 'fr' ? item.descriptionFr : item.descriptionEn}</p></div></article>; })}</div></div></section>; }

export function Benefits() { const values = [[UtensilsCrossed, 'Cuisine authentique', 'Des recettes généreuses, parfumées et préparées dans le respect des traditions.'], [Flame, 'Cuisson au tandoor', 'Des marinades travaillées et une cuisson vive dans le four traditionnel.'], [Leaf, 'Options végétariennes et véganes', 'Des choix variés et clairement indiqués pour que chacun trouve son plaisir.']]; return <section id="bienvenue" className="section home-intro"><div className="container"><SectionHeading eyebrow="Bienvenue à Montparnasse" title="Les saveurs de l’Inde et du Pakistan à Paris" intro="Currys parfumés, grillades tandoori, biryanis, pains naan et spécialités végétariennes dans une atmosphère chaleureuse au cœur de Montparnasse." /><div className="value-grid">{values.map(([Icon, title, text]) => { const ValueIcon = Icon as typeof Flame; return <article key={String(title)}><span><ValueIcon /></span><h3>{String(title)}</h3><p>{String(text)}</p></article>; })}</div></div></section>; }

const previewCategories = ['starters', 'tandoori', 'chicken', 'lamb', 'vegetarian', 'biryanis'];
export function HomeMenuPreview() { const { language } = useLanguage(); const previewItems = menuItems.filter(item => previewCategories.includes(item.categoryId)); const copy = language === 'fr' ? { eyebrow: 'Notre carte', title: 'Une cuisine faite pour être partagée', intro: 'Une sélection de plats emblématiques.', tabs: ['Entrées', 'Tandoori', 'Poulet', 'Agneau', 'Végétarien', 'Biryanis'], aria: 'Catégories de la carte', vegetarian: 'Végétarien', button: 'Voir toute la carte' } : { eyebrow: 'Our menu', title: 'Food made for sharing', intro: 'A selection of signature dishes.', tabs: ['Starters', 'Tandoori', 'Chicken', 'Lamb', 'Vegetarian', 'Biryanis'], aria: 'Menu categories', vegetarian: 'Vegetarian', button: 'View the full menu' }; return <section className="section home-menu"><div className="container"><SectionHeading eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} /><div className="menu-preview-tabs" aria-label={copy.aria}>{copy.tabs.map((category, index) => <span className={index === 0 ? 'active' : ''} key={category}>{category}</span>)}</div><div className="menu-preview-grid">{previewItems.map(item => <article key={item.id}><div><h3 className="notranslate" translate="no">{language === 'fr' ? item.name : item.englishName}</h3><p>{language === 'fr' ? item.descriptionFr : item.descriptionEn}</p></div>{item.tags?.includes('vegetarien') && <Leaf aria-label={copy.vegetarian} />}</article>)}</div><div className="center-action"><ButtonLink to="/carte">{copy.button}</ButtonLink></div></div></section>; }

export function HomeStory() { const { language } = useLanguage(); const copy = language === 'fr' ? { eyebrow: 'Notre cuisine', title: 'Une tradition de goût et d’hospitalité', text: 'Chaque plat célèbre les épices, la générosité et les traditions culinaires de l’Inde et du Pakistan.', button: 'Notre histoire', alt: `Salle chaleureuse de ${BRAND_NAME}` } : { eyebrow: 'Our cuisine', title: 'A tradition of flavour and hospitality', text: 'Every dish celebrates spices, generosity and the culinary traditions of India and Pakistan.', button: 'Our story', alt: `The warm dining room at ${BRAND_NAME}` }; return <section className="section home-story"><div className="container story-grid"><div><p className="section-label">{copy.eyebrow}</p><h2>{copy.title}</h2><p><span className="notranslate" translate="no">{BRAND_NAME}</span> — {copy.text}</p><ButtonLink to="/notre-histoire" variant="secondary">{copy.button}</ButtonLink></div><ImageWithFallback src={imagePaths.interior01} alt={copy.alt} loading="lazy" /></div></section>; }

export function GalleryPreview() { const { language } = useLanguage(); const copy = language === 'fr' ? { eyebrow: 'En images', title: 'Une atmosphère chaleureuse', intro: `La salle, les détails et les plats qui font l’expérience ${BRAND_NAME}.`, button: 'Voir la galerie' } : { eyebrow: 'In pictures', title: 'A warm atmosphere', intro: `The dining room, details and dishes that shape the ${BRAND_NAME} experience.`, button: 'View the gallery' }; return <section className="section home-gallery"><div className="container"><SectionHeading eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} /><div className="gallery-preview">{galleryItems.slice(0, 7).map((item, index) => <ImageWithFallback key={item.src} src={item.src} alt={language === 'fr' ? item.altFr : item.altEn} loading="lazy" className={`gallery-${index + 1}`} />)}</div><div className="center-action"><ButtonLink to="/galerie">{copy.button}</ButtonLink></div></div></section>; }

export function ReviewsSection() { const { language } = useLanguage(); const copy = language === 'fr' ? { eyebrow: 'Vos expériences', title: 'Ils parlent de leur visite', rating: 'Environ 1 900 avis Google', stars: '5 étoiles', source: 'Avis Google' } : { eyebrow: 'Your experiences', title: 'What guests say about their visit', rating: 'Around 1,900 Google reviews', stars: '5 stars', source: 'Google review' }; return <section className="section home-reviews"><div className="container"><div className="review-heading"><div><p className="section-label">{copy.eyebrow}</p><h2>{copy.title}</h2></div><div className="rating-lockup"><strong>4,5/5</strong><span>{copy.rating}</span></div></div><div className="review-grid">{reviews.map(review => { const text = language === 'fr' ? review.textFr : review.textEn; return <blockquote key={review.textFr}><span className="quote-mark">“</span><div className="stars" aria-label={copy.stars}><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /></div><p>« {text} »</p><cite>{copy.source}</cite></blockquote>; })}</div></div></section>; }

export function VisitSection() { const { language } = useLanguage(); const copy = language === 'fr' ? { eyebrow: 'Nous trouver', intro: 'À quelques pas de la gare Montparnasse, dans le 14e arrondissement de Paris.', route: 'Itinéraire', call: 'Appeler', reserve: 'Réserver', alt: `${BRAND_NAME} à Paris Montparnasse` } : { eyebrow: 'Find us', intro: 'A few steps from Montparnasse station, in Paris’s 14th arrondissement.', route: 'Directions', call: 'Call', reserve: 'Book', alt: `${BRAND_NAME} in Paris Montparnasse` }; return <section className="section home-visit"><div className="container visit-grid"><div><p className="section-label">{copy.eyebrow}</p><h2 className="notranslate" translate="no">{BRAND_NAME}</h2><p>{copy.intro}</p><div className="contact-lines"><a href={restaurant.mapUrl} target="_blank" rel="noreferrer"><MapPin /><span className="notranslate" translate="no">{restaurant.address.street}<br />{restaurant.address.postalCode} {restaurant.address.city}</span></a><a href={restaurant.phone.href}><Phone /><span className="notranslate" translate="no">{restaurant.phone.display}</span></a></div><div className="button-row"><ButtonLink to={restaurant.mapUrl} variant="secondary">{copy.route}</ButtonLink><ButtonLink to={restaurant.phone.href} variant="secondary">{copy.call}</ButtonLink><ButtonLink to="/reservation">{copy.reserve}</ButtonLink></div></div><ImageWithFallback src={imagePaths.interior02} alt={copy.alt} loading="lazy" /></div></section>; }

export function FinalCta() { const { language } = useLanguage(); const copy = language === 'fr' ? ['Une table vous attend à Montparnasse', 'Réserver une table', 'Commander en ligne'] : ['A table awaits you in Montparnasse', 'Book a table', 'Order online']; return <section className="final-cta"><div className="container"><p className="section-label notranslate" translate="no">{BRAND_NAME}</p><h2>{copy[0]}</h2><div className="button-row"><ButtonLink to="/reservation">{copy[1]}</ButtonLink><ButtonLink to="/commander" variant="secondary">{copy[2]}</ButtonLink></div></div></section>; }
