import { Flame, Leaf, MapPin, Phone, Star, UtensilsCrossed } from 'lucide-react';
import { galleryItems } from '../data/gallery';
import { menuItems } from '../data/menu';
import { restaurant, imagePaths } from '../data/restaurant';
import { reviews } from '../data/reviews';
import { ButtonLink, ImageWithFallback, SectionHeading } from './ui';
import { useLanguage } from '../i18n';

const dishes = [
  ['chicken-tikka', imagePaths.tikka], ['butter-chicken', imagePaths.butterChicken], ['rogan-josh', imagePaths.roganJosh],
  ['house-biryani', imagePaths.biryani], ['tandoori-mixed-grill', imagePaths.mixedGrill], ['palak-paneer', imagePaths.palakPaneer],
];

export function SignatureDishes() { const { language } = useLanguage(); const copy = language === 'fr' ? ['Les incontournables', 'Les saveurs de la maison', 'Six spécialités généreuses pour découvrir notre cuisine indienne et pakistanaise.', 'Spécialité'] : ['Signature dishes', 'Flavours of the house', 'Six generous specialities introducing our Indian and Pakistani cuisine.', 'Speciality']; return <section className="section home-dishes"><div className="container"><SectionHeading eyebrow={copy[0]} title={copy[1]} intro={copy[2]} /><div className="dish-grid">{dishes.map(([id, image]) => { const item = menuItems.find(entry => entry.id === id)!; const name = language === 'fr' ? item.name : item.nameEn; return <article className="dish-card" key={id}><ImageWithFallback src={image} alt={name} loading="lazy" /><div><span className="badge">{copy[3]}</span><h3>{name}</h3><p>{language === 'fr' ? item.descriptionFr : item.descriptionEn}</p></div></article>; })}</div></div></section>; }

export function Benefits() { const values = [[UtensilsCrossed, 'Cuisine authentique', 'Des recettes généreuses, parfumées et préparées dans le respect des traditions.'], [Flame, 'Cuisson au tandoor', 'Des marinades travaillées et une cuisson vive dans le four traditionnel.'], [Leaf, 'Options végétariennes et véganes', 'Des choix variés et clairement indiqués pour que chacun trouve son plaisir.']]; return <section id="bienvenue" className="section home-intro"><div className="container"><SectionHeading eyebrow="Bienvenue à Montparnasse" title="Les saveurs de l’Inde et du Pakistan à Paris" intro="Currys parfumés, grillades tandoori, biryanis, pains naan et spécialités végétariennes dans une atmosphère chaleureuse au cœur de Montparnasse." /><div className="value-grid">{values.map(([Icon, title, text]) => { const ValueIcon = Icon as typeof Flame; return <article key={String(title)}><span><ValueIcon /></span><h3>{String(title)}</h3><p>{String(text)}</p></article>; })}</div></div></section>; }

const previewCategories = ['starters', 'tandoori', 'chicken', 'lamb', 'vegetarian', 'biryanis'];
export function HomeMenuPreview() { const { language } = useLanguage(); const previewItems = menuItems.filter(item => previewCategories.includes(item.categoryId)); const copy = language === 'fr' ? { eyebrow: 'Notre carte', title: 'Une cuisine faite pour être partagée', intro: 'Une sélection de plats emblématiques.', tabs: ['Entrées', 'Tandoori', 'Poulet', 'Agneau', 'Végétarien', 'Biryanis'], aria: 'Catégories de la carte', vegetarian: 'Végétarien', button: 'Voir toute la carte' } : { eyebrow: 'Our menu', title: 'Food made for sharing', intro: 'A selection of signature dishes.', tabs: ['Starters', 'Tandoori', 'Chicken', 'Lamb', 'Vegetarian', 'Biryanis'], aria: 'Menu categories', vegetarian: 'Vegetarian', button: 'View the full menu' }; return <section className="section home-menu"><div className="container"><SectionHeading eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} /><div className="menu-preview-tabs" aria-label={copy.aria}>{copy.tabs.map((category, index) => <span className={index === 0 ? 'active' : ''} key={category}>{category}</span>)}</div><div className="menu-preview-grid">{previewItems.map(item => <article key={item.id}><div><h3>{language === 'fr' ? item.name : item.nameEn}</h3><p>{language === 'fr' ? item.descriptionFr : item.descriptionEn}</p></div>{item.tags?.includes('vegetarien') && <Leaf aria-label={copy.vegetarian} />}</article>)}</div><div className="center-action"><ButtonLink to="/carte">{copy.button}</ButtonLink></div></div></section>; }

export function HomeStory() { return <section className="section home-story"><div className="container story-grid"><div><p className="section-label">Notre cuisine</p><h2>Une tradition de goût et d’hospitalité</h2><p>À Vallée du Kashmir, chaque plat célèbre les épices, la générosité et les traditions culinaires de l’Inde et du Pakistan.</p><ButtonLink to="/notre-histoire" variant="secondary">Notre histoire</ButtonLink></div><ImageWithFallback src={imagePaths.interior01} alt="Salle chaleureuse de Vallée du Kashmir" loading="lazy" /></div></section>; }

export function GalleryPreview() { return <section className="section home-gallery"><div className="container"><SectionHeading eyebrow="En images" title="Une atmosphère chaleureuse" intro="La salle, les détails et les plats qui font l’expérience Vallée du Kashmir." /><div className="gallery-preview">{galleryItems.slice(0, 7).map((item, index) => <ImageWithFallback key={item.src} src={item.src} alt={item.alt} loading="lazy" className={`gallery-${index + 1}`} />)}</div><div className="center-action"><ButtonLink to="/galerie">Voir la galerie</ButtonLink></div></div></section>; }

export function ReviewsSection() { return <section className="section home-reviews"><div className="container"><div className="review-heading"><div><p className="section-label">Vos expériences</p><h2>Ils parlent de leur visite</h2></div><div className="rating-lockup"><strong>4,5/5</strong><span>Environ 1 900 avis Google</span></div></div><div className="review-grid">{reviews.map(review => <blockquote key={review.text}><span className="quote-mark">“</span><div className="stars" aria-label="5 étoiles"><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /></div><p>« {review.text} »</p><cite>{review.source}</cite></blockquote>)}</div></div></section>; }

export function VisitSection() { return <section className="section home-visit"><div className="container visit-grid"><div><SectionHeading align="left" eyebrow="Nous trouver" title="Vallée du Kashmir" intro="À quelques pas de la gare Montparnasse, dans le 14e arrondissement de Paris." /><div className="contact-lines"><a href={restaurant.mapUrl} target="_blank" rel="noreferrer"><MapPin />{restaurant.address.street}<br />{restaurant.address.postalCode} {restaurant.address.city}</a><a href={restaurant.phone.href}><Phone />{restaurant.phone.display}</a></div><div className="button-row"><ButtonLink to={restaurant.mapUrl} variant="secondary">Itinéraire</ButtonLink><ButtonLink to={restaurant.phone.href} variant="secondary">Appeler</ButtonLink><ButtonLink to="/reservation">Réserver</ButtonLink></div></div><ImageWithFallback src={imagePaths.interior02} alt="Vallée du Kashmir à Paris Montparnasse" loading="lazy" /></div></section>; }

export function FinalCta() { return <section className="final-cta"><div className="container"><p className="section-label">Vallée du Kashmir</p><h2>Une table vous attend à Montparnasse</h2><div className="button-row"><ButtonLink to="/reservation">Réserver une table</ButtonLink><ButtonLink to="/commander" variant="secondary">Commander en ligne</ButtonLink></div></div></section>; }
